version: "3.0"

services:
  polaris_simulator_dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: polaris_simulator_dev_image
    # runtime: nvidia  # This enables GPU support
    environment:
      - DISPLAY=host.docker.internal:0
      # - NVIDIA_VISIBLE_DEVICES=all  # Makes all GPUs visible
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/root/gem_ws/src/POLARIS_Robot_Manager
    stdin_open: true
    tty: true
    command: ["/bin/bash"]  # Start a bash shell interactively

  polaris_simulator_user:
    build: 
      context: .
      dockerfile: Dockerfile.user
    image: polaris_simulator_user_image
    depends_on:
      - polaris_simulator_dev
    # runtime: nvidia  # This enables GPU support
    environment:
      - DISPLAY=host.docker.internal:0
      # - NVIDIA_VISIBLE_DEVICES=all  # Makes all GPUs visible
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    command: ["/bin/bash"]  # Start a bash shell interactively
